version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_prodia_form
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  api:
    image: nevillecornelius/test-form-prodia-api:latest
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=test_prodia_form
    depends_on:
      - db
    command: node src/app.js 

  client:
    image: nevillecornelius/test-form-prodia-client:latest
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

volumes:
  db-data: